# Makefile for week 06 examples

CC=dcc
BINS=wc1 wc2 swap ptr sqcu suba replace rev1 rev2 rev3 prac

all : $(BINS)

wc1 : wc1.o
wc2 : wc2.o
swap : swap.o
ptr : ptr.o
sqcu : sqcu.o
suba : suba.o
rev1 : rev1.o
rev2 : rev2.o
rev3 : rev3.o
ptr1 : ptr1.o
replace : replace.c
prac: prac.o

johnslib.o : johnslib.c

clean :
	rm -f $(BINS) *.o
