OBJS = 06_extension_libraries_and_loading_other_image_formats.cpp
OBJ_NAME = 06_extension_libraries_and_loading_other_image_formats
FLAGS = -w
LIBS = -lSDL2 -lSDL2_image

all : $(OBJS)
	g++ $(FLAGS) $(OBJS) $(LIBS) -o $(OBJ_NAME)
