OBJS = 05_optimized_surface_loading_and_soft_stretching.cpp
OBJ_NAME = 05_optimized_surface_loading_and_soft_stretching
FLAGS = -w
LIBS = -lSDL2

all : $(OBJS)
	g++ $(FLAGS) $(OBJS) $(LIBS) -o $(OBJ_NAME)
